### ISSUE TITLE
功能请求：便捷的刷新页面

### ISSUE THREAD

**Issue by FairyScript** [Mfweb/nimingban#26]
> 版本 5153fa612bb94e979690fad78a277214733eef61

在浏览板块与串内时想要刷新必须回到顶端下拉，很不方便。
建议添加点击title刷新或其他便捷的刷新页面方式

**Comment by Mfweb** [comment]
iOS的操作方式是点击顶部回到最顶端，点击顶部刷新的话可能影响到原有交互。
后续在设置里放这个功能，默认关闭

**Comment by FairyScript** [comment]
> iOS的操作方式是点击顶部回到最顶端，点击顶部刷新的话可能影响到原有交互。
> 后续在设置里放这个功能，默认关闭

我刚刚才知道可以点击status bar回到顶端……那这个问题就没有那么紧迫了
不过对于大屏手机来说，点击顶端并不是非常容易的操作。更好的交互方式还有待讨论……

**Comment by Mfweb** [comment]
也考虑增加橙岛那样滑动时候底部显示回到顶端按钮，这两个功能都放在设置里，可以自选

**Comment by FairyScript** [comment]
> 也考虑增加橙岛那样滑动时候底部显示回到顶端按钮，这两个功能都放在设置里，可以自选

串内模式没有问题，板块视图是没有明确的「底部」的。另外，我认为A岛的内容特性决定了下拉刷新并不是一个非常舒适的操作。芦苇岛那种左滑刷新会好很多，亦或者是点击某处刷新。
我本来设想过像gmail那样添加一个多功能按钮，上滑浏览时隐藏，下滑弹出单击刷新一类的……但是不清楚RN实现起来的难度和效果，仅供参考
